services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rails db:migrate
  - bundle exec rake assets:precompile
language: ruby
rvm:
  - 2.5.3
cache: bundler
bundler_args: --without production
